---
- name: Login cli
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Show running configuration
      ios_command:
        commands:
          - show run
      register: show_run_output

    - name: Print running configuration
      debug:
        var: show_run_output.stdout_lines
