---
- name: Login cli
  hosts: all
  gather_facts: false
  connection: network_cli
  ansible_network_os: ios
    ansible_user: "261336"
    ansible_ssh_pass: "netlab"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "netlab"
    ansible_ssh_common_args: '-oKexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-rsa'
    
  tasks:
    - name: Show running configuration
      ios_command:
        commands:
          - show run
      register: show_run_output

    - name: Print running configuration
      debug:
        var: show_run_output.stdout_lines
